---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Matthew Hopkins | Denver, CO"
keywords:    "Matthew, Hopkins, DevOps Engineer, Full Stack, Web Developer"
description: "Matthew Hopkins, DevOps Engineer, Full Stack Web Developer"
source_link: "https://github.com/mrhopkins/mrhopkins.dev"
favicon:     "favicon.ico"
touch_icon:  "favicon.ico"
google_analytics_key: UA-138506829-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#3B84CF'
  green:     '#3BBA6E'
  purple:    '#635FD4'
  orange:    '#EEED17'
  turquoise: '#27B9B1'
  gray: '#757575'
  
